// Simple client-side download helpers (mock data, no backend)
export function downloadBlob(filename: string, content: BlobPart, mime = "text/plain") {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadText(filename: string, text: string) {
  downloadBlob(filename, text, "text/plain;charset=utf-8");
}

export function downloadCSV(filename: string, rows: (string | number)[][]) {
  const csv = rows
    .map((r) => r.map((v) => {
      const s = String(v ?? "");
      return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
    }).join(","))
    .join("\n");
  downloadBlob(filename, csv, "text/csv;charset=utf-8");
}

export function downloadJSON(filename: string, data: unknown) {
  downloadBlob(filename, JSON.stringify(data, null, 2), "application/json");
}

export function generateReportText(report: { id: string; title: string; date: string; type: string }) {
  const line = "═".repeat(64);
  return `${line}
GRIDBRAIN OS · ${report.type} REPORT
${line}

Report ID:   ${report.id}
Title:       ${report.title}
Generated:   ${report.date}
Region:      KA-BLR-01 (Bengaluru / BESCOM)
Classification: Internal · L3 Operator

${line}
EXECUTIVE SUMMARY
${line}
Citywide grid load is operating within nominal bounds. 3 zones
flagged at HIGH risk during evening peak (19:00–22:00 IST).
GridBrain AI recommended 4 load-shift actions and 2 reserve
mobilizations; all auto-approved per policy GB-OPS-014.

KEY METRICS
  • Total load (24h avg)        128.4 MW
  • Peak load                    184.7 MW @ 19:42
  • Forecast accuracy (MAPE)     3.7 %
  • Risk events triggered        12
  • Auto-mitigations             9
  • Operator interventions       3

ZONE HOTSPOTS
  1. Whitefield        risk 92  · 18.4/22 MW
  2. Sarjapur          risk 84  · 15.4/19 MW
  3. Electronic City   risk 81  · 16.8/21 MW

RECOMMENDATIONS
  - Activate ToU pricing in Whitefield 18:00–22:00
  - Pre-stage mobile reserve from YPR-66kV substation
  - Notify ~847 EV Mitra users near Whitefield Hub

${line}
This report was auto-generated by GridBrain OS v2.4.1.
Hash-chained · tamper-evident · regulator-ready.
${line}
`;
}
